### ISSUE TITLE
Replace var with let

### ISSUE THREAD

**Issue by ClawedCatalyst** [Bulkmailer/BulkMailer-Frontend#16]
## Description
The `var` keyword is soft-deprecated, and should not be used to redeclare existing variables. &lt;!-- more --&gt;

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/Bulkmailer/BulkMailer-Frontend/issue/JS-0085/occurrences/](https://app.deepsource.com/gh/Bulkmailer/BulkMailer-Frontend/issue/JS-0085/occurrences/)

**Comment by ClawedCatalyst** [comment]
<img width="811" alt="image" src="https://github.com/Bulkmailer/BulkMailer-Frontend/assets/97229491/e31ff843-9c55-4245-9d5f-e964275dc6c7">

Replace

var --> let

more details -> [app.deepsource.com/gh/Bulkmailer/BulkMailer-Frontend/issue/JS-0085/occurrences/](https://app.deepsource.com/gh/Bulkmailer/BulkMailer-Frontend/issue/JS-0085/occurrences/)

**Comment by lokesh-wagh** [comment]
hey can you assign me this issue

**Comment by ClawedCatalyst** [comment]
@lokesh-wagh  sure you can start :)

**Comment by lokesh-wagh** [comment]
Thanks I will work on it

**Comment by lokesh-wagh** [comment]
I think I should use different variable name's in place of i to make the code more easy to read for anyone in the future

should I do that as well??

**Comment by ClawedCatalyst** [comment]
yeah go for it :) @lokesh-wagh
