### ISSUE TITLE
the image is getting out of the box 

### ISSUE THREAD

**Issue by chaursiyasanjeet** [Bulkmailer/BulkMailer-Frontend#17]
the image or logo is getting out of the box on scrolling I want to fixed that
<img width="954" alt="image" src="https://github.com/Bulkmailer/BulkMailer-Frontend/assets/111435565/6e2f8970-f2fb-4bd9-9f18-de4f1511173a">

**Comment by ClawedCatalyst** [comment]
@chaursiyasanjeet you can start working on this
