### ISSUE TITLE
email length validation

### ISSUE THREAD

**Issue by ClawedCatalyst** [Bulkmailer/BulkMailer-Frontend#18]
<img width="1438" alt="image" src="https://github.com/Bulkmailer/BulkMailer-Frontend/assets/97229491/a9c785b5-8898-48b7-a6a5-7ae95e7b836a">

Here, on the sign-up page, the email length should be increased.

`src/components/auth/signup.jsx`

<img width="456" alt="image" src="https://github.com/Bulkmailer/BulkMailer-Frontend/assets/97229491/939ebe25-bf2d-4464-b8d9-b50150415284">

The maximum length should be increased to accommodate the email.

**Comment by Grg-Sid** [comment]
I would like to be assigned this issue

**Comment by ClawedCatalyst** [comment]
@Grg-Sid sure you can start :)
