### ISSUE TITLE
Fix: Signup form email error message is below input

### ISSUE THREAD

**Issue by devxdemon** [Bulkmailer/BulkMailer-Frontend#26]
I would like to fix the error message in the signup form for email input
here is the screenshot
![image](https://github.com/Bulkmailer/BulkMailer-Frontend/assets/87606332/4859ea24-da90-478e-96ef-1caad8678465)

**Comment by rahulxdemon** [comment]
I would like to work on this issue, can you assign this to me 🍁

**Comment by ClawedCatalyst** [comment]
Could you please provide me with details about the browser you are using and your laptop?

**Comment by rahulxdemon** [comment]
I am using Google Chrome and Lenovo Legion laptop

**Comment by ClawedCatalyst** [comment]
okay @Rahul-Palamarthi  you can start working on this :)

**Comment by rahulxdemon** [comment]
@ClawedCatalyst I will be working on it 🚀

**Comment by rahulxdemon** [comment]
@ClawedCatalyst I have fixed this issue and made a PR #29 🌟
