### ISSUE TITLE
Password Validation

### ISSUE THREAD

**Issue by vaidic-dodwani** [Bulkmailer/BulkMailer-Frontend#8]
On SignUp , using a pound (#) is stillgiving an error of password format

**Comment by Dimas-Saputra-Me** [comment]
Can I work on this issue to fix the Regex? I will use this [special character list](https://emilms.fema.gov/is_0906/groups/90.html) as guidance. Thanks

**Comment by ClawedCatalyst** [comment]
@Dimas-Saputra-Me you can start :)

**Comment by Dimas-Saputra-Me** [comment]
I have made pull-request regarding this issue on #23 
Let me know if there is any feedback or I need to do/change something. Thank you

**Comment by ClawedCatalyst** [comment]
Merged
